export { getPopulation } from './getPopulation.js'
export { getHousehold } from './getHousehold.js'
export { getSoloParent } from './getSoloParent.js'
export { getPwd } from './getPwd.js'
export { getFamily } from './getFamily.js'
export { getFemaleSegregation } from './getAgeSegregation.js'
export { getMaleSegregation } from './getAgeSegregation.js'